(TeX-add-style-hook
 "syllabus"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("geometry" "text={6.75in,9.38in}" "top=0.8in" "left=0.9in") ("microtype" "protrusion=true" "expansion=true") ("inputenc" "latin1") ("fontenc" "T1") ("xcolor" "table")))
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "leqno"
    "fleqn"
    "geometry"
    "microtype"
    "fancyhdr"
    "lastpage"
    "amssymb"
    "amsfonts"
    "amsmath"
    "amsthm"
    "eucal"
    "inputenc"
    "xspace"
    "fontenc"
    "mathptmx"
    "graphicx"
    "underscore"
    "enumerate"
    "paralist"
    "longtable"
    "datetime"
    "xcolor"
    "hyperref"
    "url"
    "pdfpages")
   (TeX-add-symbols
    '("Assignmenthead" ["argument"] 1)
    '("Coursehead" ["argument"] 0)
    '("Syllabushead" ["argument"] 0)
    '("VHeading" ["argument"] 0)
    '("HHeading" ["argument"] 0)
    '("SHeading" ["argument"] 0)
    '("Heading" ["argument"] 0)
    '("Quote" 1)
    '("Extra" 2)
    '("Web" 1)
    '("MailTo" 1)
    '("Urlx" 2)
    '("Urls" 1)
    '("tfontw" 1)
    '("tfont" 1)
    '("Subtopic" 1)
    '("Topic" 1)
    '("SubTitle" 1)
    '("Title" 1)
    '("tel" 1)
    '("Ex" 1)
    '("Sb" 1)
    '("tofill" 1)
    '("changed" 1)
    '("OpensansFont" 2)
    '("AvantgardeFont" 2)
    '("CharterFont" 2)
    '("BookmanFont" 2)
    '("CourierFont" 2)
    '("NcntrsbkFont" 2)
    '("PalatinoFont" 2)
    '("UtopiaFont" 2)
    '("HelveticaFont" 2)
    '("TimesFont" 2)
    '("descriptionlabel" 1)
    "part"
    "appendix"
    "rm"
    "sf"
    "tt"
    "bf"
    "it"
    "sl"
    "sc"
    "cal"
    "mit"
    "tableofcontents"
    "l"
    "listoffigures"
    "listoftables"
    "bibindent"
    "newblock"
    "subitem"
    "subsubitem"
    "indexspace"
    "contentsname"
    "listfigurename"
    "listtablename"
    "refname"
    "indexname"
    "figurename"
    "tablename"
    "partname"
    "appendixname"
    "abstractname"
    "section"
    "subsection"
    "subsubsection"
    "paragraph"
    "subparagraph"
    "unhcolor"
    "linewide"
    "colorfirst"
    "colornext"
    "ec"
    "el"
    "hilite"
    "Ss"
    "Se"
    "LastPage"
    "fsbfontb"
    "Fl"
    "Fm"
    "Fs"
    "CAShead"
    "syllabusfontn"
    "syllabusfontl"
    "syllabusfonts"
    "syllabusfontf"
    "syllabusfontstable"
    "LCAShead"
    "ufont"
    "tableheaderl"
    "tableheaders"
    "tableheaderh"
    "tableheader"
    "sectionmark"
    "subsectionmark"
    "footnotesize"
    "footnoterule"
    "thanks"
    "maketitle"
    "title"
    "author"
    "date"
    "and"
    "makelabel"
    "item"
    "today"
    "UrlBreaks"
    "UrlBigBreaks"
    "UrlSpecials"
    "Instructor"
    "Phone"
    "Course"
    "Coursesection"
    "Coursecrosslist"
    "Coursename"
    "Coursetext"
    "Revision"
    "Semester"
    "Office"
    "Meetingtimes"
    "Classroom"
    "Email"
    "Webpages"
    "Officehours"
    "Credits"
    "Addanddrop"
    "UndergraduatecalendarURL"
    "GradepolicyURL"
    "ImportantdatesURL"
    "FinalexamURL"
    "IntegrityURL"
    "Studenthandbook"
    "CodeofconductSHURL"
    "AttendanceSHURL"
    "CourseworkexpectURL"
    "CourseworkURL"
    "AttendanceURL"
    "AssignmentURL"
    "AccessURL"
    "TitleixURL"
    "ClrURL"
    "IncompletepolicyURL"
    "HolidaypolicySHURL"
    "InternathandbookURL"
    "AcademicsuccessURL"
    "Semesterclasses"
    "Startsemesterclasses"
    "Endsemesterclasses"
    "Lastdropdate"
    "Semesterholidays"
    "Semesterfinalexam"
    "Bookstore"
    "WithdrawalFORM"
    "BiaspolicyFORM"
    "Dayaa"
    "Dayab"
    "Dayac"
    "Dayad"
    "Dayae"
    "Dayaf"
    "Dayag"
    "Dayah"
    "Dayai"
    "Dayaj"
    "Dayak"
    "Dayal"
    "Dayam"
    "Dayan"
    "Dayao"
    "Dayap"
    "Dayaq"
    "Dayar"
    "Dayas"
    "Dayat"
    "Dayau"
    "Dayav"
    "Dayaw"
    "Dayax"
    "Dayay"
    "Dayaz"
    "Dayba"
    "Daybb"
    "Daybc"
    "Daybd"
    "Daybe"
    "Daybf"
    "Daybg"
    "Daybh"
    "Daybi"
    "Daybj"
    "Daybk"
    "Daybl"
    "Daybm"
    "Daybn"
    "Daybo"
    "Daybp"
    "Daybq"
    "Daybr"
    "Daybs"
    "Daybt"
    "Daybu"
    "Daybv"
    "Daybw"
    "Daybx"
    "Dayby"
    "Daybz"
    "Secaa"
    "Secab"
    "Secac"
    "Secad"
    "Secae"
    "Secaf"
    "Secag"
    "Secah"
    "Secai"
    "Secaj"
    "Secak"
    "Secal"
    "Secam"
    "Secan"
    "Secao"
    "Secap"
    "Secaq"
    "Secar"
    "Secas"
    "Secat"
    "Secau"
    "Secav"
    "Secaw"
    "Secax"
    "Secay"
    "Secaz"
    "Secba"
    "Secbb"
    "Secbc"
    "Secbd"
    "Secbe"
    "Secbf"
    "Secbg"
    "Secbh"
    "Secbi"
    "Secbj"
    "Secbk"
    "Secbl"
    "Secbm"
    "Secbn"
    "Secbo"
    "Secbp"
    "Secbq"
    "Secbr"
    "Secbs"
    "Secbt"
    "Secbu"
    "Secbv"
    "Secbw"
    "Secbx"
    "Secby"
    "Secbz"
    "Wrkaa"
    "Wrkab"
    "Wrkac"
    "Wrkad"
    "Wrkae"
    "Wrkaf"
    "Wrkag"
    "Wrkah"
    "Wrkai"
    "Wrkaj"
    "Wrkak"
    "Wrkal"
    "Wrkam"
    "Wrkan"
    "Wrkao"
    "Wrkap"
    "Wrkaq"
    "Wrkar"
    "Wrkas"
    "Wrkat"
    "Wrkau"
    "Wrkav"
    "Wrkaw"
    "Wrkax"
    "Wrkay"
    "Wrkaz"
    "Wrkba"
    "Wrkbb"
    "Wrkbc"
    "Wrkbd"
    "Wrkbe"
    "Wrkbf"
    "Wrkbg"
    "Wrkbh"
    "Wrkbi"
    "Wrkbj"
    "Wrkbk"
    "Wrkbl"
    "Wrkbm"
    "Wrkbn"
    "Wrkbo"
    "Wrkbp"
    "Wrkbq"
    "Wrkbr"
    "Wrkbs"
    "Wrkbt"
    "Wrkbu"
    "Wrkbv"
    "Wrkbw"
    "Wrkbx"
    "Wrkby"
    "Wrkbz")
   (LaTeX-add-labels
    "lastpage")
   (LaTeX-add-environments
    '("thebibliography" 1)
    "description"
    "abstract"
    "verse"
    "quotation"
    "quote"
    "titlepage"
    "figure"
    "table"
    "theindex")
   (LaTeX-add-pagestyles
    "headings"
    "myheadings")
   (LaTeX-add-counters
    "part"
    "section"
    "subsection"
    "subsubsection"
    "paragraph"
    "subparagraph"
    "figure"
    "table")
   (LaTeX-add-lengths
    "abovecaptionskip"
    "belowcaptionskip")
   (LaTeX-add-xcolor-definecolors
    "darkred"
    "darkbrown"
    "darkgreen"
    "darkblue"
    "linkblue"
    "unhlink"
    "unhblue"
    "pink"
    "paleyellow1"
    "paleyellow2"
    "gold"
    "darkgold"
    "palegreen1"
    "palegreen2"
    "paleblue1"
    "paleblue2"
    "paleyellow"
    "DeepPink"
    "gray10"
    "gray20"
    "gray30"
    "gray40"
    "gray45"
    "gray50"
    "gray60"
    "gray70"
    "gray80"
    "gray90"
    "gray98"
    "gray99"))
 :latex)

