#+TITLE: Calculus Schedule
#+STARTUP: showall indent align inlineimages nologdone

* Week 1 (WF classes only)
** Intro to Class
*** Syllabus
*** Overview of class
*** Assumed knowledge
**** important values of trig functions
**** graphing basic functions
**** basic algebra (simplifying expressions, esp fractions like (a+b)/a)
**** solve an equation for a specified term
** Functions
*** Input/Output machine, domain/image (vert. line test)
*** Examples: real world (seating chart, etc), polynomials, rational functions, absolute value, piecewise, algebraic functions, trig/exp/log
* Week 2
** Inverse Functions
*** Horizontal line test
*** Exp and Log
*** Trig and ArcTrig
** Algebra of Functions
*** Shift, Stretch, Reflect
*** Add/Sub
*** Mult/Divide
*** Compose
** Limits (Graphically)
*** Motivate with tangent lines
*** Definition
*** Graphical intuition
*** One-sided limits
**** Thm. two-sided limit exists iff each one-sided exists
*** To infinity
* Week 3
** Limits (Analytically)
*** Limit laws
*** Find limits for the following
**** piecewise
**** lim f(x) as x-->a and f(a) DNE
*** Squeeze theorem
** Continuity
*** Graphical intuition
*** Definition
*** Theorems: compatiblility w algebra of functions (esp composition), IVT
** Introducing the derivative
*** Derivative as slope: geometry
**** tangent line w slope f(x + delta x) - f(x) / delta x as delta x --> 0
*** Derivative as slope: analysis
**** Definition of derivative at a point
*** Derivative as ratio between change in input to change in output.  
Ex: Given f(x)=x^2.  Then the input is x and the output is
f(x).  So if we nudge the input a bit by dx, the
corresponding output is
f(x)+df=(x+dx)^2=x^2+2xdx+(dx)^2. Cancel out f(x)=x^2 on
each side to get df = 2xdx+(dx)^2. But dx is soooo small
that squaring it equals zero (kind of but either way we
ignore it). So we get df = 2xdx.  

*** Examples from physics
* Week 4
** Derivative as a function
*** Start w derivative at a point and let point vary
**** Notation: f', df/dx = d/dx(f(x)), dy/dx = d/dx (y), y', d/dx(-) as operator
***** Exercise: write d/dx (f(x)) in plain english, so "take the x-derivative of the function f", or d/dx(x^2)*d/dx(2x) is take the derivative of x^2 and the derivative of 2x then multiply them together, etc
*** Examples w analysis and geometry
**** Fix an f. Graph f. Draw tangent lines at various places on f. Plot their slopes on another graph (surprise that's f').  Draw more and more tanget lines and plot their slopes. Fill in graph of f'.  How do we find closed form of f'? Use definition.
**** Another way to look at it:
***** Draw a function f. df/dx asks, if the input changes a bit, then how much does the output change?  We get this little triangle whose hypotenuse is the slope of the line 


*** Higher order derivatives
*** Non-differentiable functions
**** Diff ==> Cont
**** Geometry: diff means no corners, cont means no breaks
** Rules of differentiation
*** Finding derivatives using limit definition can be hard. Maybe there's an easier way? Consider, human powered car (Fred flinstone) vs motor powered car.
**** Abstraction allows us to find limits of *classes* of functions, not *instances* of functions
***** d/dx (c) = 0 (Note general c, not, say, 9. Now we never need to do that again)
INTUITION: c never changes, its constant, so when we nudge
the input, c remains the same, hence the change is 0
***** d/dx (x^n) = nx^{n-1} (Note general n, not say 4. now we never need to do that again)
GEOMETRIC INTUITION FOR x^2,x^3,ETC.  Draw x^2 as a square
with both sides x.  Then lets nudge x a bit to add on dx to
both sides.  How much as the area changed?  We get three
boxes: x*dx, x*dx, and dx*dx.  But dx*dx is negligable
leaving us with 2xdx.  Draw x^3 as a cube and increase all
sides by dx.  By how much did the area increase?  We get 3
new boxes: x*x*dx, x*dx*x, dx*x*x and 3 other boxes dx*dx*x,
dx*x*dx, x*dx*dx, and a small cube dx*dx*dx.  But all these
new shapes have zero area except for the first three because
dx^2 is negligable.  Hence the area has increased by
3x^2*dx.  
***** d/dx (cf) = cf'
GEOMETRIC INTUITION: Draw a box, one side is f the other is
c. Then nudge the input give a new square adding sides df
and dc and df*dc but the latter two are zero leaving us with
only the new box with width df and legnth c. Hence the newly
added area is c*df.
***** d/dx (f + g) = f' + g'
****** Use geometry to understand this.  Graph two functions. Also, draw vertical lines from the x-axis to the graph for each. Color code this.  then the summed function is the addition of the two lines at the same place.  To find d(fx+gx), we observe that the way the summed line changes in the sum of the two individuals lines from fx and gx.  WATCH 3BROWN1BLUE video for ideas.
***** Now we know how to derive polynomials. We used abstraction to find *four* principals (i.e. theorems) and from these four, we can differentiate infinitely many kinds of functions in this more high-powered way.
*** Examples 
**** finding n-th order derivatives of given polynomials
**** tangent lines (give hint: derivative is slope)
** More rules of differentiaion: product and quotient
*** Complecated functions are often build from multiplying or dividing simpler functions. Maybe there's a way to derive hard functions by deriving the easier functions of which they are comprised.  Just like breaking a hard task into easier piece.  
**** For example: deriving (\pi x^7 - 5.231 x^4 + 13)(x^4 - 4x^2 + 5x) or (x^3 + 3x^2 - 12 x) / (x^5 - 5x^3 + 1) are both hard.  But they are build from polynomials which are easier to derive.  Here, use a slide that shows d/dx (hard functions) = ? but we know d/dx (each polynomial) = the answer.
**** Analogy w art: drawing a person is hard, but if we break it down into drawing a head, legs, etc, the task becomes easier.  
*** Show product rule and quotient rule. 
**** geometric intuition for product rule

Given a function f*g, draw it as a square with side lengths
f and g. Then extend each side out by dx to get three
smaller boxes with sides df*g, dg*f and dx*dx.  Then
d(f*g) is the change in area when adding these boxes so its
the sum of the three boxes.  However dx*dx is so small we
ignore it leaving behind the two boxes hence the formuls. 
*** Examples, include combining product and quotient rule.  
* Week 5
** Derivative of trig functions
*** Start with (sin x)' using definition then getting to part where you use cos h - 1 / h and sin h / h
*** Show that lim sinx/x =1 and lim cosx-1/x = 0 with animation
**** Do examples using these facts, like lim_{x->0} sin(4x)/x, etc
*** Return to (sin x)' derivation and complete.  Repeat for (cos x)'
**** thm: derivative of sin, cos
**** Do some examples, mix with other diff rules
*** thm: use diff rules to find (tanx)', (secx)', etc. Leave one or two as exercise
**** give table of trig derivatives.  
** Derivatives in the world: rates of change
*** Things in the world change in time: populations, velocity of pendulum, amounts of money in bank accounts, etc.  Solicit examples from audience.  These physical phenominon can be modeled using derivatives. This allows us to make predictions and reason about physical processes.  
*** Physics examples
**** Show viedo of mars rover landing. Engineers know how fast the rover approaches the mars based on gravity and mass, etc. This knowledge allows them to design systems to counteract the velocity so that it lands at the desired speed (too fast it breaks). That is a much more complex situation involving many variables. We are starting with one variable.  Draw silly picture of rover landing.  There are several things at play: the position of the rover abouve the ground; but the position is changing and the measure of the rate at which it's changing is called velocity, which we'll see is a first derivative; but also because of gravity, the veloctiy is changing by getting faster and faster and the rate of change of velocity is called accelleration, which we'll see is a second derivative.
**** Do a stone example: throw a stone up in the air from height of s0 with velocity v0. What equation can describe it's height?  Differential equations give a meethod for figuring this out, but we'll sort of reason out way through it.  Hint: it's an upside down parabola, so something like s(t) = -at^2 + bt +c.  Find a,b,c.  Note c is the height the rock starts at so s0.  Velocity is first derivative so s'(t) = -2at+b and accelleratino is section derivative to s''(t)=-2a.  Only acceleration is gravity, so 32 ft/s/s towards the earth giving -2a=-32 so a=32.  Next solve for b.  
***** Example: stone follows position s(t)= -16t^2 + 64t + 96. Find velocity and acceleration functions. Find highest point reached. What velocity doe sthe stone strike the ground?  
****** For 2nd, set s'(t)=0 and solve for t.  Argue by graphing s'(t) and showing that the pint s'=0 with when the stone is the highest.
*** Business examples
**** We run a business making those circular things on the backs of phones. The cost per widget is C(x)= 10,000 + 0.10x - 0.05x^2 (start up + cost/widget - economies of scale). Two common questions are (1) what is the avg cost per widget, and (2) what is the marginal cost, i.e. if we make n widgets, what is the average cost of making a the next one?  
***** What is the average cost per widget if we make 10 widgets (ans C(10)/10) Repeat question for high numbers. Conclude avg cost is C(x)/x.  
***** Say we made 1000 widgets and want to know the total cost of making 100 more. That is C(1100)-C(1000). The average cost of those next 100 widgets is C(1100)-C(1000)/100.  To find the marginal cost, we use abstraction through calculus.  In general, the equation is C(x+delta x) - C(x) / delta x. As we take delta x to be smaller and smaller, i.e. delta x --> 0, we get C'(x).  
**** Do some examples.
** The chain rule

*** A motivating example 

Suppose that Yuri runs 5x faster than Umberto and Unmberto
runs 4x faster than Xander, ie dy/du=4. Then Yuri runs 5 times faster
than Xander, ie du/dx.  How many time faster than Xander does Yuri
run, ie what is dy/dx? ANS: 5*4 = 20 That is dy/dx=dy/du*du/dx

Image of above (YURI) ---5x---> (Umberto) ---4x---> (Xander)
gives the composition is 20x.  

Let y mean the position of Yuri, u the position of Umberto,
and x the position of Xander.  Then dy/dt is the velocity of
Yuri, du/dt is the velocity of Umberto, dx/dt the velocity
of Xander.  


* Week 6
** Mon 24 Feb
** Wed 26 Feb
** Fri 28 Feb
* Week 7
** Mon 02 Mar
** Wed 04 Mar
** Fri 06 Mar
* Week 8
** Mon 09 Mar
** Wed 11 Mar
** Fri 13 Mar
* Week 9 
** Mon 16 Mar // Spring Break
** Wed 18 Mar // Spring Break
** Fri 20 Mar // Spring Break
* Week 10
** Mon 23 Mar
** Wed 25 Mar
** Fri 27 Mar
* Week 11
** Mon 30 Mar
** Wed 01 Apr
** Fri 03 Apr
* Week 12
** Mon 06 Apr
** Wed 08 Apr
** Fri 10 Apr
* Week 13
** Mon 13 Apr
** Wed 15 Apr
** Fri 17 Apr
* Week 14
** Mon 20 Apr
** Wed 22 Apr
** Fri 24 Apr
* Week 15
** Mon 27 Apr
** Wed 29 Apr
** Fri 01 May
* Week 16
** Mon 04 May // Final Class
** Wed 06 May // Reading Day
** Fri 08 May
